# Generated by Django 4.2.29 on 2026-04-27 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('Personal_Information', '0001_initial'), ('Personal_Information', '0002_education'), ('Personal_Information', '0003_alter_education_options_alter_education_score'), ('Personal_Information', '0004_certification_alter_education_options_and_more'), ('Personal_Information', '0005_experience'), ('Personal_Information', '0006_profile_profile_picture'), ('Personal_Information', '0007_websettings'), ('Personal_Information', '0008_delete_websettings'), ('Personal_Information', '0009_skill'), ('Personal_Information', '0010_rename_wikipedia_profile_reddit'), ('Personal_Information', '0011_alter_profile_linkedin')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(max_length=200)),
                ('provider_name', models.CharField(max_length=200)),
                ('provider_icon', models.URLField(blank=True, null=True)),
                ('verification_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=50)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200)),
                ('work_type', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(max_length=100)),
                ('location', models.TextField()),
                ('github', models.URLField(blank=True, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True)),
                ('discord', models.URLField(blank=True, null=True)),
                ('reddit', models.URLField(blank=True, null=True)),
                ('dev', models.URLField(blank=True, null=True)),
                ('about', models.TextField()),
                ('location_url', models.URLField(blank=True, null=True)),
                ('profile_picture', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('percentage', models.PositiveIntegerField(help_text='Enter value between 0 and 100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
    ]
