# Generated by Django 4.2.29 on 2026-04-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('Website_settings', '0001_initial'), ('Website_settings', '0002_seosettings'), ('Website_settings', '0003_websettings_background')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_keywords', models.CharField(blank=True, max_length=300)),
                ('meta_image', models.URLField(blank=True)),
                ('canonical_url', models.URLField(blank=True)),
                ('robots', models.CharField(default='index, follow', help_text='Example: index, follow or noindex, nofollow', max_length=50)),
                ('google_site_verification', models.CharField(blank=True, max_length=200)),
                ('bing_site_verification', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'SEO Setting',
                'verbose_name_plural': 'SEO Settings',
            },
        ),
        migrations.CreateModel(
            name='WebSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon', models.URLField(help_text='URL of website favicon')),
                ('title', models.CharField(max_length=200)),
                ('second_title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('background', models.URLField(default='hello', help_text='URL of website favicon')),
            ],
            options={
                'verbose_name': 'Web Setting',
                'verbose_name_plural': 'Web Settings',
            },
        ),
    ]
