# Generated by Django 6.0.3 on 2026-03-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon', models.URLField(help_text='URL of website favicon')),
                ('title', models.CharField(max_length=200)),
                ('second_title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Web Setting',
                'verbose_name_plural': 'Web Settings',
            },
        ),
    ]
