# Generated by Django 6.0.3 on 2026-03-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_keywords', models.CharField(blank=True, max_length=300)),
                ('meta_image', models.URLField(blank=True)),
                ('canonical_url', models.URLField(blank=True)),
                ('robots', models.CharField(default='index, follow', help_text='Example: index, follow or noindex, nofollow', max_length=50)),
                ('google_site_verification', models.CharField(blank=True, max_length=200)),
                ('bing_site_verification', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'SEO Setting',
                'verbose_name_plural': 'SEO Settings',
            },
        ),
    ]
