# Generated by Django 4.2.29 on 2026-04-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website_settings', '0002_seosettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='websettings',
            name='background',
            field=models.URLField(default='hello', help_text='URL of website favicon'),
            preserve_default=False,
        ),
    ]
