# Generated by Django 4.2.29 on 2026-04-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('Profile_url', '0001_initial'), ('Profile_url', '0002_rename_profile_profile_url')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('profile_url', models.URLField(max_length=500, unique=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
