"""
Django settings for Webapp project.

Generated by 'django-admin startproject' using Django 4.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7$a4xd0$7q&1+oi$+c=5et0&@m*5t7wqa%fzbginmzbrf_s$ev'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition
INSTALLED_APPS = [
    'django_daisy',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "django.contrib.humanize",
    "Personal_Information.apps.PersonalInformationConfig",
    "Website_settings.apps.WebsitesettingsConfig",
    "Project.apps.ProjectConfig",
    "Article.apps.ArticleConfig",
    "Contact.apps.ContactConfig",
    "Profile_url.apps.ProfileUrlConfig",
    'tinymce',
]
TINYMCE_DEFAULT_CONFIG = {
    "height": 650,
    "width": "100%",
    "toolbar_sticky": True,
    "menubar": True,
    "verify_html": False,
    "cleanup": False,
    "cleanup_on_startup": False,
    "valid_elements": "*[*]",
    "extended_valid_elements": "*[*]",
    "custom_elements": "*[*]",
    "skin": "oxide-dark",
    "content_css": "dark",
    "plugins": """
        preview searchreplace autolink autosave save
        directionality code visualblocks visualchars fullscreen
        image link media template codesample table charmap
        hr pagebreak nonbreaking anchor toc insertdatetime
        advlist lists wordcount help quickbars emoticons
        paste autoresize
    """,
    "toolbar": """
        undo redo | blocks fontfamily fontsize |
        bold italic underline strikethrough |
        forecolor backcolor |
        alignleft aligncenter alignright alignjustify |
        bullist numlist outdent indent |
        link image media table codesample |
        removeformat | fullscreen preview code
    """,
    "color_map": [
        "#282A36", "Dracula Background",
        "#44475A", "Current Line",
        "#F8F8F2", "Foreground",
        "#6272A4", "Comment",
        "#8BE9FD", "Cyan",
        "#50FA7B", "Green",
        "#FFB86C", "Orange",
        "#FF79C6", "Pink",
        "#BD93F9", "Purple",
        "#FF5555", "Red",
        "#F1FA8C", "Yellow",
    ],
    "font_family_formats": """
        Poppins=Poppins,sans-serif;
        Roboto=Roboto,sans-serif;
        Open Sans=Open Sans,sans-serif;
        Lato=Lato,sans-serif;
        Montserrat=Montserrat,sans-serif;
        Inter=Inter,sans-serif;
        Ubuntu=Ubuntu,sans-serif;
        Arial=arial,helvetica,sans-serif;
        Georgia=georgia,serif;
        Times New Roman=times new roman,times,serif;
        Fira Code=Fira Code,monospace;
        JetBrains Mono=JetBrains Mono,monospace;
        Source Code Pro=Source Code Pro,monospace;
        Consolas=consolas,monospace;
        Courier New=courier new,courier,monospace;
    """,
    "codesample_languages": [
        {"text": "Python", "value": "python"},
        {"text": "Django", "value": "python"},
        {"text": "JavaScript", "value": "javascript"},
        {"text": "TypeScript", "value": "typescript"},
        {"text": "HTML/XML", "value": "markup"},
        {"text": "CSS", "value": "css"},
        {"text": "SCSS", "value": "scss"},
        {"text": "JSON", "value": "json"},
        {"text": "Bash", "value": "bash"},
        {"text": "SQL", "value": "sql"},
        {"text": "C", "value": "c"},
        {"text": "C++", "value": "cpp"},
        {"text": "Java", "value": "java"},
        {"text": "PHP", "value": "php"},
        {"text": "Go", "value": "go"},
    ],
    "codesample_global_prismjs": True,
    "codesample_content_css": "dark",
    "content_style": """
        body {
            background-color: #282A36;
            color: #F8F8F2;
        }

        pre {
            background-color: #1E1F29;
            color: #F8F8F2;
            padding: 15px;
            border-radius: 8px;
            overflow-x: auto;
            font-family: 'Fira Code', 'JetBrains Mono', monospace;
            font-size: 14px;
        }

        code {
            font-family: 'Fira Code', 'JetBrains Mono', monospace;
        }
    """,
    "branding": False,
    "statusbar": True,
    "autosave_ask_before_unload": True,
    "quickbars_selection_toolbar": "bold italic | quicklink h2 h3 blockquote",
    "paste_as_text": False,
}
DAISY = {
    "APPS": {
        "Personal_Information": {
            "icon": "user"
        }
    }
}
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Webapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Webapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_URL = "static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
